CREATE TABLE IF NOT EXISTS `lts_job_log_po` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `gmt_created` bigint(20) DEFAULT NULL COMMENT '日志创建时间',
  `log_time` bigint(20) DEFAULT NULL  COMMENT '日志记录时间',
  `log_type` varchar(32) DEFAULT NULL COMMENT '日志类型',
  `success` tinyint(11) DEFAULT NULL COMMENT '成功与否',
  `msg` text COMMENT '消息',
  `code` varchar(32) DEFAULT NULL COMMENT '消息编码',
  `task_tracker_identity` varchar(64) DEFAULT NULL COMMENT '执行节点唯一标识',
  `level` varchar(32) DEFAULT NULL COMMENT '日志记录级别',
  `task_id` varchar(64) DEFAULT NULL COMMENT '客户端ID',
  `job_id` varchar(64) DEFAULT '' COMMENT '服务端生成ID',
  `priority` int(11) DEFAULT NULL COMMENT '优先级',
  `submit_node_group` varchar(64) DEFAULT NULL COMMENT '提交节点group',
  `task_tracker_node_group` varchar(64) DEFAULT NULL COMMENT '执行节点group',
  `ext_params` text COMMENT '额外参数',
  `need_feedback` tinyint(4) DEFAULT NULL COMMENT '是否需要反馈',
  `cron_expression` varchar(32) DEFAULT NULL COMMENT 'cron表达式',
  `trigger_time` bigint(20) DEFAULT NULL COMMENT '触发时间',
  `retry_times` int(11) DEFAULT NULL COMMENT '重试次数',
  PRIMARY KEY (`id`),
  KEY `log_time` (`log_time`),
  KEY `task_id_task_tracker_node_group` (`task_id`,`task_tracker_node_group`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;