CREATE TABLE IF NOT EXISTS `lts_admin_jvm_memory` (
            `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
            `gmt_created` bigint(20) NULL DEFAULT NULL,
            `identity` varchar(64) DEFAULT NULL,
            `timestamp` bigint(20) NULL DEFAULT NULL,
            `node_type` varchar(32) NULL DEFAULT NULL,
            `node_group` varchar(64) NULL DEFAULT NULL,
            `heap_memory_committed` bigint(20) NULL DEFAULT NULL,
            `heap_memory_init` bigint(20) NULL DEFAULT NULL,
            `heap_memory_max` bigint(20) NULL DEFAULT NULL,
            `heap_memory_used` bigint(20) NULL DEFAULT NULL,
            `non_heap_memory_committed` bigint(20) NULL DEFAULT NULL,
            `non_heap_memory_init` bigint(20) NULL DEFAULT NULL,
            `non_heap_memory_max` bigint(20) NULL DEFAULT NULL,
            `non_heap_memory_used` bigint(20) NULL DEFAULT NULL,
            `perm_gen_committed` bigint(20) NULL DEFAULT NULL,
            `perm_gen_init` bigint(20) NULL DEFAULT NULL,
            `perm_gen_max` bigint(20) NULL DEFAULT NULL,
            `perm_gen_used` bigint(20) NULL DEFAULT NULL,
            `old_gen_committed` bigint(20) NULL DEFAULT NULL,
            `old_gen_init` bigint(20) NULL DEFAULT NULL,
            `old_gen_max` bigint(20) NULL DEFAULT NULL,
            `old_gen_used` bigint(20) NULL DEFAULT NULL,
            `eden_space_committed` bigint(20) NULL DEFAULT NULL,
            `eden_space_init` bigint(20) NULL DEFAULT NULL,
            `eden_space_max` bigint(20) NULL DEFAULT NULL,
            `eden_space_used` bigint(20) NULL DEFAULT NULL,
            `survivor_committed` bigint(20) NULL DEFAULT NULL,
            `survivor_init` bigint(20) NULL DEFAULT NULL,
            `survivor_max` bigint(20) NULL DEFAULT NULL,
            `survivor_used` bigint(20) NULL DEFAULT NULL,
            PRIMARY KEY (`id`),
            KEY `idx_identity` (`identity`),
            KEY `idx_timestamp` (`timestamp`)
            );